
name: radio_mosaic_premium
description: Premium Radio Mosaic App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  flutter_animate: ^4.5.0

flutter:
  uses-material-design: true
